LIST=LIB
EARLY_DIRS=c support-safety regex smmu drvr m compat socket z bzip2 lzma expat cache strm jpeg png tiff tomcrypt openpam login socket-io-sock shm_lock kalman misc ncurses2 mmutil pps spi-master qnxalgs devcr openssl certicom_toolkits slog2 json qh utlfd libiconv radius xml2 catalog icu
LATE_DIRS=dma lua mDNSResponder cares curl ipsec-tools libxo io-sock io-pkt wmpinfo aoa fsmerkle qcrypto tcg qfim qfim-client
include recurse.mk
