ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)
include $(MKFILES_ROOT)/qmacros.mk

NAME=wdtkick-sc
LIBS+=drvr login

USEFILE=$(PROJECT_ROOT)/$(SECTION)/$(NAME)-$(SECTION).use

include $(PROJECT_ROOT)/$(SECTION)/pinfo.mk


#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk


-include $(PROJECT_ROOT)/roots.mk
