ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

include $(MKFILES_ROOT)/qmacros.mk

define PINFO
PINFO DESCRIPTION=System Controller driver for the NXP i.MX8x
endef

EXTRA_INCVPATH += $(PROJECT_ROOT)/public/sys

USEFILE =
INSTALLDIR = sbin
LIBS = drvrS nxp_imx8_sci login



#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk


