ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

ifndef CLASS
CLASS=imx8lpspi
endif

NAME = spi-$(CLASS)
USEFILE=$(PROJECT_ROOT)/$(NAME).use
EXTRA_SILENT_VARIANTS+=$(SECTION)

LIBS += drvr
ifdef EDMA_SUPPORT
LIBS += dma-edma
CCFLAGS += -DEDMA_SUPPORT
endif

define PINFO
PINFO DESCRIPTION=
endef

include $(MKFILES_ROOT)/qmacros.mk
-include $(PROJECT_ROOT)/roots.mk

include $(PROJECT_ROOT)/pinfo.mk

#Removes the default -Wl,-Bsymbolic from the link commandline
LDVFLAG_dll= -L.


#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

