ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

include $(MKFILES_ROOT)/qmacros.mk

define PINFO
PINFO DESCRIPTION=I2C Driver for i.MX8 low power I2C interface
endef

NAME := i2c-$(NAME)
USEFILE = $(PROJECT_ROOT)/$(NAME).use
INSTALLDIR = sbin
LIBS = i2c-master  drvrS



#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk


